<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="millihex">

  <!-- Properties -->
  <xacro:property name="torso_mass" value="0.01" />
  <xacro:property name="torso_x" value="0.14" />
  <xacro:property name="torso_y" value="0.04" />
  <xacro:property name="leg_link_mass" value="0.0008" />
  <xacro:property name="leg_link_x" value="0.03" />
  <xacro:property name="leg_link_y" value="0.02" />
  <xacro:property name="pcb_thickness_z" value="0.0005" />
	<xacro:property name="foot_kp" value="1000.0" />
	<xacro:property name="foot_kd" value="1000.0" />
	<xacro:property name="foot_mu1" value="10.0" />
  <xacro:property name="foot_mu2" value="10.0" />


  <!-- Calculate Moment of Inertia of Box -->
  <xacro:macro name="box_inertia" params="mass x y z">
    <inertia ixx="${mass*(y*y+z*z)/12}" ixy = "0" ixz = "0"
             iyy="${mass*(x*x+z*z)/12}" iyz = "0"
             izz="${mass*(x*x+z*z)/12}" />
  </xacro:macro>


  <!-- Base and Torso Definition -->
  <xacro:macro name="millihex_torso" params="">
    <link name="base_link">
    </link>

    <link name="torso">
      <inertial>
        <origin xyz="0 0 ${pcb_thickness_z / 2}" rpy="0 0 0" />
        <mass value="${torso_mass}" />
        <xacro:box_inertia mass="${torso_mass}" x="0.14" y="0.04" z="0.0005" />
      </inertial>
      <collision>
        <origin xyz="0 0 0.00025" rpy="0 0 0"/>
        <geometry>
          <box size="0.14 0.04 0.0005" />
        </geometry>
      </collision>
      <visual>
        <origin rpy="0.0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="0.14 0.04 0.0005" />
        </geometry>
      </visual>
    </link>
    <!-- TODO: insert torso frictions -->
    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="torso"/>
    </joint>
  </xacro:macro>


  <!-- Leg Link Definition -->
  <xacro:macro name="millihex_leg_link" params="leg_number link_number link_mass x_length y_length z_length">
    <link name="leg${leg_number}_link${link_number}">
      <inertial>
        <origin xyz="0 0 ${z_length / 2}" rpy="0 0 0" />
        <mass value="0.01" />
        <xacro:box_inertia mass="0.0008" x="${x_length}" y="${y_length}" z="${z_length}" />
      </inertial>
      <collision>
        <origin xyz="0 0 0.00025" rpy="0 0 0"/>
        <geometry>
          <box size="0.02 0.03 0.0005" />
        </geometry>
      </collision>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="0.02 0.03 0.0005" />
        </geometry>
      </visual>
    </link>
    <!-- TODO: insert link frictions -->
  </xacro:macro>


  <!-- Leg Joint Transmission -->
  <xacro:macro name="leg_transmission" params="leg_number joint_number">
    <transmission name="leg${leg_number}_joint${joint_number}_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="leg${leg_number}_joint${joint_number}">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="leg${leg_number}_joint${joint_number}_motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  
  <!-- Assemble Leg -->
  <xacro:macro name="millihex_leg" params="leg_number">
    <xacro:millihex_leg_link leg_number="" joint_number="" />
    
    <joint name="leg${leg_number}_joint" type="fixed">
      <parent link="lowerleg_M${number}_link"/>
      <child link="footM${number}_link"/>
      <origin xyz="0 0 0.06" rpy="0 0 0"/>
    </joint>

    <joint name="leg1_joint1" type="revolute">
      <parent link="torso" />
      <child link="leg1_link1" />
      <origin xyz="0.08333333 -0.05 0" rpy="0 0 0" />
      <limit lower="-1.5708" upper="1.5708" effort="1" velocity="1"/>
      <axis xyz="1 0 0" />
    </joint>

  </xacro:macro>


  <!-- Assemble Body -->
  <xacro:macro name="millihex_body" params="leg_number joint_number">
    <xacro:millihex_torso />
  </xacro:macro>


  <!-- Add Gazebo Control Library -->
  <xacro:macro name="millihex_control" params="namespace">
    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/${namespace}</robotNamespace>
      </plugin>
    </gazebo>
  </xacro:macro>
  

  <!-- Build Robot by Filling in Macro Parameters -->
  <xacro:millihex_torso />


  <xacro:millihex_control namespace="millihex" />

</robot>