millihex:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  # Leg 1
  leg1_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg1_joint1
    pid: {p: 0.1, i: 0.0, d: 0.0}

  leg1_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg1_joint2
    pid: {p: 0.1, i: 0.0, d: 0.0}

  leg1_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg1_joint3
    pid: {p: 0.1, i: 0.0, d: 0.0}

  # Leg 2
  leg2_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg2_joint1
    pid: {p: 0.1, i: 0.0, d: 0.0}

  leg2_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg2_joint2
    pid: {p: 0.1, i: 0.0, d: 0.0}

  leg2_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg2_joint3
    pid: {p: 0.1, i: 0.0, d: 0.0}

  # To add more just add them here as the first one